var BANK_LIST = [
  { name: 'MAYBANK', logo: 'https://logo.clearbit.com/maybank.com' },
  { name: 'CIMB BANK', logo: 'https://logo.clearbit.com/cimb.com' },
  { name: 'PUBLIC BANK', logo: 'https://logo.clearbit.com/publicbank.com.my' },
  { name: 'RHB BANK', logo: 'https://logo.clearbit.com/rhb.com.my' },
  { name: 'HONG LEONG BANK', logo: 'https://logo.clearbit.com/hlb.com.my' },
  { name: 'AMBANK', logo: 'https://logo.clearbit.com/ambank.com.my' },
  { name: 'UOB MALAYSIA', logo: 'https://logo.clearbit.com/uob.com.my' },
  { name: 'OCBC BANK', logo: 'https://logo.clearbit.com/ocbc.com.my' },
  { name: 'STANDARD CHARTERED', logo: 'https://logo.clearbit.com/sc.com' },
  { name: 'HSBC MALAYSIA', logo: 'https://logo.clearbit.com/hsbc.com.my' },
  { name: 'CITIBANK', logo: 'https://logo.clearbit.com/citibank.com.my' },
  { name: 'BANK ISLAM MALAYSIA', logo: 'https://logo.clearbit.com/bankislam.com.my' },
  { name: 'BANK RAKYAT', logo: 'https://logo.clearbit.com/bankrakyat.com.my' },
  { name: 'BSN', logo: 'https://logo.clearbit.com/bsn.com.my' },
  { name: 'AFFIN BANK', logo: 'https://logo.clearbit.com/affinbank.com.my' },
  { name: 'ALLIANCE BANK', logo: 'https://logo.clearbit.com/alliancebank.com.my' },
  { name: 'BANK MUAMALAT', logo: 'https://logo.clearbit.com/muamalat.com.my' },
  { name: 'MBSB BANK', logo: 'https://logo.clearbit.com/mbsbbank.com' },
  { name: 'AGROBANK', logo: 'https://logo.clearbit.com/agrobank.com.my' },
  { name: 'AL RAJHI BANK', logo: 'https://logo.clearbit.com/alrajhibank.com.my' },
  { name: 'KUWAIT FINANCE HOUSE', logo: 'https://logo.clearbit.com/kfh.com.my' },
  { name: 'BANK OF CHINA (MALAYSIA)', logo: 'https://logo.clearbit.com/bankofchina.com.my' },
  { name: 'ICBC (MALAYSIA)', logo: 'https://logo.clearbit.com/icbc.com.my' },
  { name: 'SMBC (MALAYSIA)', logo: 'https://logo.clearbit.com/smbc.com' },
  { name: 'MIZUHO BANK (MALAYSIA)', logo: 'https://logo.clearbit.com/mizuho.com' },
  { name: 'MUFG BANK (MALAYSIA)', logo: 'https://logo.clearbit.com/mufg.com' },
  { name: 'DEUTSCHE BANK', logo: 'https://logo.clearbit.com/db.com' },
  { name: 'J.P. MORGAN', logo: 'https://logo.clearbit.com/jpmorgan.com' },
  { name: 'BNP PARIBAS (MALAYSIA)', logo: 'https://logo.clearbit.com/bnpparibas.com.my' },
  { name: 'GOLDMAN SACHS', logo: 'https://logo.clearbit.com/goldmansachs.com' },
  { name: 'BANK OF AMERICA', logo: 'https://logo.clearbit.com/bankofamerica.com' },
  { name: 'MAYBANK ISLAMIC', logo: 'https://logo.clearbit.com/maybank.com' },
  { name: 'CIMB ISLAMIC', logo: 'https://logo.clearbit.com/cimb.com' },
  { name: 'PUBLIC ISLAMIC BANK', logo: 'https://logo.clearbit.com/publicislamicbank.com.my' },
  { name: 'RHB ISLAMIC', logo: 'https://logo.clearbit.com/rhb.com.my' },
  { name: 'HONG LEONG ISLAMIC', logo: 'https://logo.clearbit.com/hlb.com.my' },
  { name: 'AFFIN ISLAMIC', logo: 'https://logo.clearbit.com/affinbank.com.my' },
  { name: 'AMBANK ISLAMIC', logo: 'https://logo.clearbit.com/ambank.com.my' },
  { name: 'ALLIANCE ISLAMIC', logo: 'https://logo.clearbit.com/alliancebank.com.my' },
  { name: 'HSBC AMANAH', logo: 'https://logo.clearbit.com/hsbc.com.my' },
  { name: 'STANDARD CHARTERED SAADIQ', logo: 'https://logo.clearbit.com/sc.com' },
  { name: 'OCBC AL-AMIN', logo: 'https://logo.clearbit.com/ocbc.com.my' },
  { name: 'SME BANK', logo: 'https://logo.clearbit.com/smebank.com.my' },
  { name: 'EXIM BANK', logo: 'https://logo.clearbit.com/eximbank.com.my' },
  { name: 'BANK PEMBANGUNAN MALAYSIA', logo: 'https://logo.clearbit.com/bankpembangunan.com.my' },
  { name: 'AEON BANK (MALAYSIA)', logo: 'https://logo.clearbit.com/aeonbank.com.my' },
  { name: 'GX BANK', logo: 'https://logo.clearbit.com/gxbank.my' },
  { name: 'BOOST BANK', logo: 'https://logo.clearbit.com/boostbank.online' }
];

var BANK_GENERIC_LOGO = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><rect width="24" height="24" rx="4" fill="#e2e8f0"/><path d="M12 6l8 4H4l8-4zm-6 6h12v6H6v-6zm3 1v3m3-3v3m3-3v3" fill="none" stroke="#475569" stroke-width="1.5"/></svg>'
);
